#!/bin/bash
set -ex

function require() {
  if [[ $# -lt 1 ]]; then
    echo usage: require package-name
    echo
    echo if you want to force install a package use `require false package-name`
    echo you might want to do that if a package installs a binary with a different name
    return 0
  fi

  local binary=${1}
  shift
  local packages=${*:-$binary}
  command -v "$binary" >/dev/null 2>&1 && return 0
  # normally you would quote $packages, but we want multiple package
  # install support (`ruby ruby-dev`, not `"ruby ruby-dev"`)
  DEBIAN_FRONTEND=noninteractive apt install -y $packages
}

export -f require

echo "running setup..."

for script in /root/scripts/*; do $script; done
